require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe QuestoesController do

  # This should return the minimal set of attributes required to create a valid
  # Questao. As you add validations to Questao, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # QuestoesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all questoes as @questoes" do
      questao = Questao.create! valid_attributes
      get :index, {}, valid_session
      assigns(:questoes).should eq([questao])
    end
  end

  describe "GET show" do
    it "assigns the requested questao as @questao" do
      questao = Questao.create! valid_attributes
      get :show, {:id => questao.to_param}, valid_session
      assigns(:questao).should eq(questao)
    end
  end

  describe "GET new" do
    it "assigns a new questao as @questao" do
      get :new, {}, valid_session
      assigns(:questao).should be_a_new(Questao)
    end
  end

  describe "GET edit" do
    it "assigns the requested questao as @questao" do
      questao = Questao.create! valid_attributes
      get :edit, {:id => questao.to_param}, valid_session
      assigns(:questao).should eq(questao)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Questao" do
        expect {
          post :create, {:questao => valid_attributes}, valid_session
        }.to change(Questao, :count).by(1)
      end

      it "assigns a newly created questao as @questao" do
        post :create, {:questao => valid_attributes}, valid_session
        assigns(:questao).should be_a(Questao)
        assigns(:questao).should be_persisted
      end

      it "redirects to the created questao" do
        post :create, {:questao => valid_attributes}, valid_session
        response.should redirect_to(Questao.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved questao as @questao" do
        # Trigger the behavior that occurs when invalid params are submitted
        Questao.any_instance.stub(:save).and_return(false)
        post :create, {:questao => {}}, valid_session
        assigns(:questao).should be_a_new(Questao)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Questao.any_instance.stub(:save).and_return(false)
        post :create, {:questao => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested questao" do
        questao = Questao.create! valid_attributes
        # Assuming there are no other questoes in the database, this
        # specifies that the Questao created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Questao.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => questao.to_param, :questao => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested questao as @questao" do
        questao = Questao.create! valid_attributes
        put :update, {:id => questao.to_param, :questao => valid_attributes}, valid_session
        assigns(:questao).should eq(questao)
      end

      it "redirects to the questao" do
        questao = Questao.create! valid_attributes
        put :update, {:id => questao.to_param, :questao => valid_attributes}, valid_session
        response.should redirect_to(questao)
      end
    end

    describe "with invalid params" do
      it "assigns the questao as @questao" do
        questao = Questao.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Questao.any_instance.stub(:save).and_return(false)
        put :update, {:id => questao.to_param, :questao => {}}, valid_session
        assigns(:questao).should eq(questao)
      end

      it "re-renders the 'edit' template" do
        questao = Questao.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Questao.any_instance.stub(:save).and_return(false)
        put :update, {:id => questao.to_param, :questao => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested questao" do
      questao = Questao.create! valid_attributes
      expect {
        delete :destroy, {:id => questao.to_param}, valid_session
      }.to change(Questao, :count).by(-1)
    end

    it "redirects to the questoes list" do
      questao = Questao.create! valid_attributes
      delete :destroy, {:id => questao.to_param}, valid_session
      response.should redirect_to(questoes_url)
    end
  end

end
